[build]
  # Directory to publish (the build output folder)
  publish = "build/web"
  
  # Build command - Install Flutter first, then build
  command = """
    # Set Flutter path
    export FLUTTER_ROOT="$HOME/flutter"
    export PATH="$FLUTTER_ROOT/bin:$PATH"
    
    # Install Flutter if not cached
    if [ ! -d "$FLUTTER_ROOT" ]; then
      echo "Installing Flutter..."
      git clone https://github.com/flutter/flutter.git -b stable --depth 1 "$FLUTTER_ROOT"
    else
      echo "Flutter found in cache"
    fi
    
    # Verify Flutter installation
    flutter doctor -v
    flutter config --no-analytics
    
    # Get dependencies and build
    flutter pub get
    flutter build web --release --base-href=/
  """

[build.environment]
  # Specify Flutter channel and version
  FLUTTER_CHANNEL = "stable"
  # Cache Flutter installation between builds
  NODE_VERSION = "18"

# Redirect rules for Flutter web routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

